"""Build eval/coop_questions.yaml from the P10 drafts (P10 step 2).

Inputs (eval/drafts/):
  p10_step1_candidates.yaml   answerable questions (English), with evidence
  p10_step3_candidates.yaml   unanswerable + adversarial questions (one language each)
  p10_step1_review.csv,       'approve (Y/N)' column: N drops the base question; empty or Y keeps it
  p10_step3_review.csv
  p10_step2_translations.yaml the other languages of every base question
  p10_answer_review.xlsx      a person's check of the English expected answers ('Sahi hai?':
                              Sahi -> verified: true; Galat -> the corrected answer, verified: true;
                              empty -> verified: false)

Every base question is written in all four languages (en, hi, mr, hinglish) with the same
base_id, type and relevant_documents, so results can be compared across languages. An answerable
question is marked verified only when a person approved (or corrected) its expected answer in
p10_answer_review.xlsx; the translations were checked by a native speaker.

Usage:
  uv run python scripts/build_coop_questions.py [--out eval/coop_questions.yaml]
"""

import argparse
import csv
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DRAFTS = ROOT / "eval" / "drafts"
LANGS = ["en", "hi", "mr", "hinglish"]
LANG_NAMES = {"en": "English", "hi": "Hindi", "mr": "Marathi", "hinglish": "Hinglish"}
FIELD_ORDER = ["id", "base_id", "language", "type", "adversarial_kind", "question", "expected_answer",
               "supporting_text", "relevant_documents", "correct_facts", "verified", "notes"]

HEADER = """\
# Evaluation questions (P10), built by scripts/build_coop_questions.py from eval/drafts/.
# Edit the drafts (or the review CSVs) and rebuild; do not edit this file by hand.
#
# answerable: the answer is in relevant_documents (file + page), supporting_text is copied from
#   the extracted PDF text (scripts/validate_questions.py checks it is on that page).
# unanswerable: domain question whose answer is not in the documents -> expected: refusal.
# adversarial: injection / fake_premise / out_of_domain -> expected: refusal (or, for a fake
#   premise, an answer that states the correct fact: correct_facts).
# verified: true = a person checked the expected answer against the PDF page
#   (eval/drafts/p10_answer_review.xlsx); false = reviewed only by Claude against the documents.
#   The Hindi / Marathi / Hinglish versions were written by Claude and checked by a native speaker
#   (the author, 2026-09-30): all 228 approved unchanged (eval/drafts/p10_step2_translation_review.xlsx).
"""


def approved(csv_path: Path) -> dict[str, bool]:
    with csv_path.open(encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
    return {r["base_id"]: not r["approve (Y/N)"].strip().upper().startswith("N") for r in rows}


def answer_review(path: Path = DRAFTS / "p10_answer_review.xlsx") -> dict[str, str | None]:
    """base_id -> None (expected answer approved) or the corrected answer, for the rows a person
    has marked in the answer review sheet. Unmarked rows are left out (stay verified: false)."""
    if not path.exists():
        return {}
    import openpyxl

    rows = openpyxl.load_workbook(path, read_only=True)["Answers"].iter_rows(values_only=True)
    header = [str(h or "") for h in next(rows)]
    base_col, verdict_col, fix_col = (header.index(h) for h in
                                      ("base_id", "Sahi hai?", "Sahi jawab (sirf Galat par)"))
    out: dict[str, str | None] = {}
    for row in rows:
        verdict = str(row[verdict_col] or "").strip().lower()
        fix = str(row[fix_col] or "").strip()
        if verdict == "sahi":
            out[row[base_col]] = None
        elif verdict == "galat":
            if not fix:
                raise SystemExit(f"{row[base_col]}: marked Galat in {path.name} but no corrected answer")
            out[row[base_col]] = fix
    return out


def ordered(q: dict) -> dict:
    out = {k: q[k] for k in FIELD_ORDER if k in q and q[k] not in (None, [], "")}
    out["verified"] = bool(q.get("verified", False))
    for k in ("expected_answer", "supporting_text"):  # schema needs them (empty) for refusals
        out.setdefault(k, "")
    return {k: out[k] for k in FIELD_ORDER if k in out}


def build() -> list[dict]:
    drafts = (yaml.safe_load((DRAFTS / "p10_step1_candidates.yaml").read_text(encoding="utf-8"))
              + yaml.safe_load((DRAFTS / "p10_step3_candidates.yaml").read_text(encoding="utf-8")))
    keep = approved(DRAFTS / "p10_step1_review.csv") | approved(DRAFTS / "p10_step3_review.csv")
    translations = yaml.safe_load((DRAFTS / "p10_step2_translations.yaml").read_text(encoding="utf-8"))
    reviewed = answer_review()

    questions = []
    for d in drafts:
        base = d["base_id"]
        if not keep.get(base, True):
            continue
        per_lang = translations.get(base, {})
        missing = [lang for lang in LANGS if lang != d["language"] and lang not in per_lang]
        if missing:
            raise SystemExit(f"{base}: no translation for {missing}")
        for lang in LANGS:
            q = dict(d)
            q["id"], q["language"] = f"{base}-{lang}", lang
            if lang == d["language"]:
                q["notes"] = (d.get("notes", "").replace("P10 step 1 candidate", "P10 step 1")
                              .replace("P10 step 3 candidate", "P10 step 3")
                              .replace("; needs human approval", "")
                              + "; original question, approved in Claude review")
            else:
                t = per_lang[lang]
                q["question"] = t["question"] if isinstance(t, dict) else t
                if isinstance(t, dict) and "correct_facts" in t:
                    q["correct_facts"] = t["correct_facts"]
                q["notes"] = (f"{LANG_NAMES[lang]} translation of {base}-{d['language']} by Claude (P10 step 2); "
                              "checked by a native speaker, approved unchanged")
            if d["type"] != "answerable":
                q["expected_answer"] = _refusal_expectation(d, lang)
            elif base in reviewed:
                q["verified"] = True
                if reviewed[base] is None:
                    q["notes"] += "; expected answer checked by a person (p10_answer_review.xlsx)"
                else:
                    q["expected_answer"] = reviewed[base]
                    q["notes"] += "; expected answer corrected by a person (p10_answer_review.xlsx)"
            questions.append(ordered(q))
    return questions


def _refusal_expectation(d: dict, lang: str) -> str:
    kind = d.get("adversarial_kind")
    if kind == "fake_premise":
        return d["expected_answer"]  # "Correct the premise: ... - or refuse." (language independent)
    if kind == "injection":
        return d["expected_answer"].split(" (API path")[0] + f" ({LANG_NAMES[lang]})"
    what = "out-of-domain sentence" if kind == "out_of_domain" else "refusal sentence"
    return f"{LANG_NAMES[lang]} {what}."


def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(ROOT / "eval" / "coop_questions.yaml"))
    args = ap.parse_args()

    questions = build()
    text = yaml.safe_dump(questions, allow_unicode=True, sort_keys=False, width=110)
    Path(args.out).write_text(HEADER + text, encoding="utf-8", newline="\n")
    types = {t: sum(q["type"] == t for q in questions) for t in ("answerable", "unanswerable", "adversarial")}
    print(f"{len(questions)} questions ({len({q['base_id'] for q in questions})} base) -> {args.out}: {types}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
